Create .gitignore
kayjeee/Hello-Microverse-two pull request #1
Opened 2023-02-15 09:34 UTC by kayjeee

comparing the master branch and the mykagisoBranch

2023-02-15 09:36 UTC, kayjeee commented
making a pull request for very first time

2023-02-15 09:58 UTC, GedeonTS requested changes
# STATUS: CHANGES REQUIRED :recycle: :

Hi <STUDENT_MENTION>, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif">

## Highlights :tophat:  :+1: 
- .gitinore, HTML, and CSS files are created

## Required Changes ♻️
- Kindly make sure to add HTML/CSS linter checkS to your project by following these [instructions](https://github.com/microverseinc/linters-config) in the project requirements
- I think it would be better to customize your README for your current project by assuming the only optional section is FAQ, While also making the MIT license link is no longer broken by creating a license file.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 09:58 UTC, GedeonTS commented on .gitignore
- As per the project requirements, kindly create a test.md file, then add node_modules and test.md here gitignre so that they are both ignored by git :recycle:

2023-02-16 07:09 UTC, kayjeee commented on .gitignore
Hi @GedeonTS 
Thank you for the suggestions,
I made changes as you suggested,

please let me know if anything could be done beter

2023-02-16 17:08 UTC, divinecharlotte requested changes
Hi @kayjeee    👋, 

## STATUS: REQUESTED CHANGES ♻️ 

Good job so far 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media3.giphy.com/media/h7u3pLvYK3HfQ4yXxW/giphy.gif"/>

### To Highlight 🎯 💡 

1. Good commit messages 👍 


## Required Changes ♻️

- kindly checkout this point from the previous reviewer and implement it  👇 
![aq](https://user-images.githubusercontent.com/60146030/219429156-a5039fc4-f6fe-4c1a-ad23-d026a64b44cd.PNG)

- [ ] I can see you have done a lot of work on this PR👍 but let's make our branch look more professional by giving them a descriptive name remember "Branch should have a name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section')"😉  example on your case you can name it like `Hello-Microverse` kindly checkout to a new branch and use the correct name and mention the old PR in the new PR

- [ ] I can see that you tried to implement some required changes on your readme but still there some requirements which are missing am listing them below:

1. consider removing Microverse log from your readme or add yours if you have one to make your project personal
2. consider removing these brackets on this title "[your_project_name]" this will make it look more good
3. consider editing this section "Tech Stack" by making it contain the related techs to your project to avoid confusion for the project visitors
4. kindly remove this section "Live Demo" as you are not deploying your project 
5. consider adding more information on this section "Getting Started' so as people who may want to use it might to get any blocker like on this point "Setup" you can edit it like this 

Clone this repository to your desired folder do :
` git clone  git@github.com:kayjeee/Hello-Microverse-two.git ` 
consider doing that on all points of this section

6. kindly consider removing one author from this section as you are the only author of this project and put in consideration adding your working social media links to this section
7. kindly add linters to your project by following the instruction in this [link](https://github.com/microverseinc/linters-config/tree/master/html-css)  and remember all your linters should be green
8. consider going back 👇 to the below instructions and make sure you implement them before you request for another review
![22](https://user-images.githubusercontent.com/60146030/219437304-c42b0ded-7e4a-4fed-af23-04365c4ff5ee.PNG)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @divinecharlotte  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 18:50 UTC, closed without merging