Hello microverse
kayjeee/Hello-Microverse-two pull request #2
Opened 2023-02-16 21:40 UTC by kayjeee

2023-02-16 22:34 UTC, kayjeee commented
fixed the issues suggested I fix

2023-02-16 23:39 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @kayjeee, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  Fair README file. :heavy_check_mark: 

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)


## Required Changes ♻️

- [x] The content of your `index.html` is supposed to be `Hello Microverse` not `Header, My Header`. Kindly fix that.

![your-content](https://user-images.githubusercontent.com/26597432/219511708-eed286ca-5b8d-460c-bc69-68d75700dded.png)

Project Requirements

![project-rqt](https://user-images.githubusercontent.com/26597432/219511856-3cd3612f-b577-4ef2-a129-413efbb5b7e1.png)

- [ ] It is required that your PR must have a descriptive summary that says what work you've done in the PR. At this moment, your PR has no descriptive summary. Kindly add descriptive summary to your PR.

![pr-desc](https://user-images.githubusercontent.com/26597432/219512070-957c1237-204f-40cf-aad4-3bcf72cd69a0.png)

- [ ] Your PR also has conflict you need to resolve before your project can be approve. 

![your-conflict](https://user-images.githubusercontent.com/26597432/219512421-e342b20b-a293-4a04-b2b7-7bf4a93cf7a5.png)



_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 23:39 UTC, Qoosim commented on .github/workflows/linters.yml
> +          if [ -d "node_modules/" ]; then echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."; echo -e "\e[1;32mYou can set u
- [ ] Linters test do not run on this PR. Kindly follow this [link](https://github.com/microverseinc/linters-config/tree/master/html-css) to set it up properly

2023-02-16 23:39 UTC, Qoosim commented on README.md
> +- [Tech Stack](#tech-stack)
- [ ] Kindly follow this [link]() to make a professional README file. All the headings must be present except FAQ which is optional. You can simply put `N/A` under any heading that is not relevant to your project  at this moment.

2023-02-16 23:39 UTC, Qoosim commented on README.md
>  <!-- LICENSE -->
- [ ] Kindly follow this [link](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to properly set up MIT license for your project.

2023-02-17 00:43 UTC, kayjeee commented on .github/workflows/linters.yml
> +          if [ -d "node_modules/" ]; then echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."; echo -e "\e[1;32mYou can set u
I really struggle with this  issue
I can't get linters to work
any help would be appreciated 
should I start a new project on GitHub?

2023-02-17 01:46 UTC, Owusu-Desmond requested changes
Hi @kayjeee , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: :red_circle: :red_circle: 

You have submitted a project, that has falling linter errors.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-17 10:55 UTC, joskalenda approved these changes
| STATUS: APPROVED ✅ |
|------------------------|
| Hi @kayjeee , 🥰|
| Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉  |
| <img src="https://media2.giphy.com/media/2NpKgBuUZtXpu/giphy.gif"/> |

### Highlights
✅ ... Green linters
✅ ... Great communication with the reviwer

---------
### Optional suggestions

> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### Cheers and Happy coding!👏👏👏
-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 13:11 UTC, merged